export const roomAmenities: string[] = [
  'Clothes Rack',
  'Drying Rack',
  'Dryer',
  'Fan',
  'Heating',
  'Air Conditioning',
  'Wardrobe',
  'Soundproofing',
  'Carpeted Floors',
  'Fireplace',
  'Mosquito Net',
  'Sitting Area',
  'Electric Blanket',
  'Tile Floors',
  'Parquet Floors',
  'Hardwood Floors',
  'Ironing Board',
];
export const bathroomAmenities: string[] = [
  'Hot Water',
  'Shower',
  'Bathtub',
  'Hair Dryer',
  'ToiletPaper',
  'Bath Robes',
  'Slippers',
  'SpaTub',
  'Toilet',
  'Free Toiletries',
  'Toilet Soap',
  'Private Bathroom',
  'Shared Bathroom',
  'Towels',
];
export const mediaAndTechnologyAmenities: string[] = [
  'TV',
  'Cable TV',
  'Satellite TV',
  'Flat Screen TV',
  'Radio',
  'CD Player',
  'DVD Player',
  'iPod Docking Station',
  'WiFi',
  'Mp3 Player',
  'Telephone',
  'Computer',
  'Game Console',
  'VideoGames',
];
export const foodAndDrinkAmenities: string[] = [
  'Dining Table',
  'Dining Chairs',
  'Dining Area',
  'Stovetop',
  'Oven',
  'Toaster',
  'Refrigerator',
  'Microwave',
  'Dish washer',
  'Espresso Machine',
  'Coffee Maker',
  'Tea Maker',
  'Kettle',
  'Barbecue Grill',
  'Outdoor Dining Area',
  'Outdoor Seating',
  'Outdoor Fireplace',
  'Outdoor Table',
  'Outdoor Chairs',
];
export const servicesAndExtrasAmenities: string[] = [
  'Executive Lounge Access',
  'Business Center',
  'Laundry Service',
  'Dry Cleaning Service',
  'Alarm Clock',
  'Wake Up Call',
  'Towel Delivery',
  'Toiletries Delivery',
  'Room Service',
  'Breakfast In Room',
  'Ironing Service',
];
export const outdoorAndViewAmenities: string[] = [
  'Balcony',
  'Terrace',
  'View',
  'Patio',
  'Garden View',
  'Pool View',
  'Sea View',
  'Mountain View',
  'Forest View',
  'Lake View',
  'River View',
  'Beach View',
  'City View',
  'Park View',
  'Landmark View',
  'Quiet Street View',
];
export const accessibilityAmenities: string[] = [
  'Room Is Located On The Ground Floor',
  'Room Is Completely Wheelchair Accessible',
  'Room Is Accessible By Elevator',
  'Room Is Accessible By Stairs',
  'Toilet Is Wheelchair Accessible',
];
export const entertainmentAndFamilyServicesAmenities: string[] = [
  'Baby Safety Gate',
  'Board Games',
  'Childrens Club',
  'Childrens Menu',
  'Childrens Play Area',
  'Childrens Playground',
  'Books For Children',
  'Baby Sitting Service',
  'Child Safety Socket Cover',
  'Child Safety Lock',
];
export const facilitiesAmenities: string[] = [
  'Parking',
  'Swimming Pool',
  'Gym',
  'Breakfast',
  'Dinner',
  'Lunch',
  'Room Service',
  'Airport Shuttle',
  'Babysitting',
  'Laundry',
  'Dry Cleaning',
  'Beach Front',
  'Free Parking',
  'Spa',
  'Sauna',
  'Steam Room',
  'Hot Tub',
  'Fitness Center',
  'Yoga',
  'Massage',
  'Garden',
];
